#pragma once

#include <vulkan/vulkan.h>
#include <vulkan/vk_enum_string_helper.h>
#include <vk_mem_alloc.h>

#include <fmt/core.h>

#include <glm/mat4x4.hpp>
#include <glm/vec4.hpp>

#include <entt/entt.hpp>

#include <magic_enum/magic_enum.hpp>

#define VK_CHECK(x)                                                     \
    do {                                                                \
        VkResult err = x;                                               \
        if (err) {                                                      \
            fmt::println("Detected Vulkan error: {}", string_VkResult(err)); \
            abort();                                                    \
        }                                                               \
    } while (0)

template <typename T>
inline static constexpr std::string GetNullSeparated()
{
    // Generated by AI
    std::string result;
    constexpr auto names = magic_enum::enum_names<T>();
    for (std::size_t i = 0; i < names.size() - 1; i++) 
    {
        result += names[i];
        result += '\0';
    }
    result += '\0'; // Final null terminator
    return result;
}

// Type aliases
typedef uint32_t        u32;
typedef uint16_t        u16;
typedef uint8_t         u8;
typedef int32_t         s32;
typedef int16_t         s16;
typedef int8_t          s8;
typedef unsigned int    uint;

using Entity = entt::entity;

enum RenderMode_
{
    RenderMode_FinalColor,
    RenderMode_TexCoord0,
    RenderMode_Tangent,
    RenderMode_Bitangent,
    RenderMode_GeometryNormal,
    RenderMode_ShadingNormal,
    RenderMode_BaseColor,
    RenderMode_NormalMap,
    RenderMode_Metallic,
    RenderMode_Roughness,
    RenderMode_AmbientOcclusion,
    RenderMode_Emission,
    RenderMode_WorldPos,
    RenderMode_ViewDir,
    RenderMode_Wireframe,
    RenderMode_Depth,
    kRenderModeCount
};
using RenderMode = int;

const std::string kRenderModeStr = GetNullSeparated<RenderMode_>();

enum ModelResource_
{
    ModelResource_CompareAmbientOcclusion,
    ModelResource_CompareBaseColor,
    ModelResource_CompareMetallic,
    ModelResource_CompareRoughness,
    ModelResource_DamagedHelmet,
    ModelResource_FlightHelmet,
    ModelResource_Lantern,
    ModelResource_MetalRoughSpheres,
    ModelResource_NormalTangentMirrorTest,
    ModelResource_NormalTangentTest,
    ModelResource_OrientationTest,
    ModelResource_SciFiHelmet,
    ModelResource_Sponza,
    ModelResource_TextureEncodingTest,
    ModelResource_TextureLinearInterpolationTest,
    kModelResourceCount
};
using ModelResource = int;

const std::string kModelResourceStr = GetNullSeparated<ModelResource_>();

enum TonemapMode_
{
	TonemapMode_None,
	TonemapMode_Reinhard,
	TonemapMode_ACES,
    TonemapMode_PBRNeutral,
	kTonemapModeCount
};
using TonemapMode = int;

const std::string kTonemapModeStr = GetNullSeparated<TonemapMode_>();

enum PipelineType
{
    PipelineType_Background,
    PipelineType_Rasterized,
    PipelineType_Tonemap,
    PipelineType_RayTraced,
    kPipelineTypeCount,
};

enum PipelineMode_
{
    PipelineMode_Rasterized = PipelineType_Rasterized,
    PipelineMode_RayTraced = PipelineType_RayTraced,
    kPipelineModeCount,
};
using PipelineMode = int;

const std::string kModelPaths[kModelResourceCount] =
{
    "../../assets/Khronos/CompareAmbientOcclusion/glTF-Binary/CompareAmbientOcclusion.glb",
    "../../assets/Khronos/CompareBaseColor/glTF-Binary/CompareBaseColor.glb",
    "../../assets/Khronos/CompareMetallic/glTF-Binary/CompareMetallic.glb",
    "../../assets/Khronos/CompareRoughness/glTF-Binary/CompareRoughness.glb",
    "../../assets/Khronos/DamagedHelmet/glTF-Binary/DamagedHelmet.glb",
    "../../assets/Khronos/FlightHelmet/glTF/FlightHelmet.gltf",
    "../../assets/Khronos/Lantern/glTF-Binary/Lantern.glb",
    "../../assets/Khronos/MetalRoughSpheres/glTF-Binary/MetalRoughSpheres.glb",
    "../../assets/Khronos/NormalTangentMirrorTest/glTF-Binary/NormalTangentMirrorTest.glb",
    "../../assets/Khronos/NormalTangentTest/glTF-Binary/NormalTangentTest.glb",
    "../../assets/Khronos/OrientationTest/glTF-Binary/OrientationTest.glb",
    "../../assets/Khronos/SciFiHelmet/glTF/SciFiHelmet.gltf",
    "../../assets/Khronos/Sponza/glTF/Sponza.gltf",
    "../../assets/Khronos/TextureLinearInterpolationTest/glTF-Binary/TextureLinearInterpolationTest.glb",
    "../../assets/Khronos/TextureEncodingTest/glTF-Binary/TextureEncodingTest.glb"
};

struct AllocatedImage 
{
    VkImage         image;
    VkImageView     imageView;
    VmaAllocation   allocation;
    VkExtent3D      imageExtent;
    VkFormat        imageFormat;
};

struct AllocatedBuffer 
{
    VkBuffer            buffer;
    VmaAllocation       allocation;
    VmaAllocationInfo   info;
};

struct Vertex
{
    glm::vec3 position;
    float uvX;
    glm::vec3 normal;
    float uvY;
    glm::vec4 color;
    glm::vec3 tangent;
    float handedness;

    static VkVertexInputBindingDescription GetBindingDescription()
    {
        VkVertexInputBindingDescription bindingDescription{};
        bindingDescription.binding = 0;
        bindingDescription.stride = sizeof(Vertex);
        bindingDescription.inputRate = VK_VERTEX_INPUT_RATE_VERTEX;
        return bindingDescription;
    }

    static std::array<VkVertexInputAttributeDescription, 6> GetAttributeDescriptions()
    {
        std::array<VkVertexInputAttributeDescription, 6> attributeDescriptions{};

        attributeDescriptions[0].binding    = 0;
        attributeDescriptions[0].location   = 0;
        attributeDescriptions[0].format     = VK_FORMAT_R32G32B32_SFLOAT;
        attributeDescriptions[0].offset     = offsetof(Vertex, position);

        attributeDescriptions[1].binding    = 0;
        attributeDescriptions[1].location   = 1;
        attributeDescriptions[1].format     = VK_FORMAT_R32_SFLOAT;
        attributeDescriptions[1].offset     = offsetof(Vertex, uvX);

        attributeDescriptions[2].binding    = 0;
        attributeDescriptions[2].location   = 2;
        attributeDescriptions[2].format     = VK_FORMAT_R32G32B32_SFLOAT;
        attributeDescriptions[2].offset     = offsetof(Vertex, normal);

        attributeDescriptions[3].binding    = 0;
        attributeDescriptions[3].location   = 3;
        attributeDescriptions[3].format     = VK_FORMAT_R32_SFLOAT;
        attributeDescriptions[3].offset     = offsetof(Vertex, uvY);

        attributeDescriptions[4].binding    = 0;
        attributeDescriptions[4].location   = 4;
        attributeDescriptions[4].format     = VK_FORMAT_R32G32B32A32_SFLOAT;
        attributeDescriptions[4].offset     = offsetof(Vertex, color);

        attributeDescriptions[5].binding    = 0;
        attributeDescriptions[5].location   = 5;
        attributeDescriptions[5].format     = VK_FORMAT_R32G32B32A32_SFLOAT;
        attributeDescriptions[5].offset     = offsetof(Vertex, tangent);

        return attributeDescriptions;
    }
};

namespace gpu
{
// holds the resources needed for a mesh
struct MeshBuffers {

    AllocatedBuffer indexBuffer;
    AllocatedBuffer vertexBuffer;
    VkDeviceAddress vertexBufferAddress;
};

// push constants for our mesh object draws
//struct RenderPushConstants {
//    glm::mat4 viewProj;
//    glm::mat4 model;
//};
//struct RenderPushConstantsFrag {
//    glm::vec4 camPos;
//    glm::ivec4 renderMode;
//};

struct alignas(16) PushConstants
{
    glm::mat4   viewProj;
    glm::mat4   model;
    glm::vec4   camPos;
    glm::ivec4  renderMode;
};

struct SceneData {
    glm::mat4 view;
    glm::mat4 proj;
    glm::mat4 viewproj;
    glm::vec4 ambientColor;
    glm::vec4 sunlightDirection; // w for sun power
    glm::vec4 sunlightColor;
};

//struct AccelerationStructure
//{
//    VkAccelerationStructureKHR accel{};
//    VkDeviceAddress            address{};
//    Buffer                     buffer;  // Underlying buffer
//};

}